# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/groundbnb_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Jskabylie89!

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
# Change secret key to use 256 bits
jwt.secret=this-is-the-super-secret-key-that-everyone-may-be-using-in-dev-mode-nadir
jwt.expiration=86400000
